version: '3'

services:
  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - ./tmp/db:/data/db  

  api:
    build:
      context: .
    image: ghcr.io/democraciarnred/asambleasclimaticas-api:latest
    ports:
      - "4000:3000"
    env_file:
      - .env
    links:
      - mongo
    depends_on:
      - mongo      